---
abstract: 'pack your dependencies onto your script file'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-FatPacker
no_index:
  directory:
    - t
    - inc
requires:
  perl: 0
resources:
  homepage: http://git.shadowcat.co.uk/gitweb/gitweb.cgi?p=p5sagit/App-FatPacker.git
  repository: git://git.shadowcat.co.uk/p5sagit/App-FatPacker.git
version: 0.009012
